import Head from "next/head";
import Contact from "../components/Contact";
import About from "../components/About";
import Main from "../components/Main";
import Projects from "../components/Projects";
import Skill from "../components/Skill";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Louis Muriuki MERN Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles&family=Kalam:wght@300&family=Lato:ital,wght@0,100;0,300;0,400;1,100;1,300;1,400&family=Poppins&display=swap" rel="stylesheet"></link>
      </Head>
      <Main />
      <About />
      <Skill />
      <Projects />
      <Contact />
    </div>
  );
}
