import Head from 'next/head'
import Contact from '../components/Contact'
import About from '../components/About'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skill from '../components/Skill'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Louis Muriuki MERN Full Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skill/>
      <Projects/>
      <Contact/>
    </div>

  )
}
